site_name: 逻辑与形而上学
site_author: 一之江
site_url: https://shiinahiiragi.github.io/note/
repo_name: ShiinaHiiragi/note
repo_url: https://github.com/ShiinaHiiragi/note/
dev_addr: 127.0.0.1:3000

theme:
  name: material
  font:
    text: false
  palette:
    - scheme: default
      primary: indigo
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: 切换到白色主题
    - scheme: defualt
      primary: white
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: 切换到原主题

  language: zh
  favicon: assets/favicon.png
  icon:
    logo: material/cube-outline
  features:
    - content.code.copy
    - navigation.tracking
    - navigation.tabs
    - navigation.expand
    - navigation.top
    - toc.follow
    - toc.integrate
    - search.highlight
    - search.share

markdown_extensions:
  - meta
  - admonition
  - attr_list
  - def_list
  - footnotes
  - pymdownx.details
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true

plugins:
  - search

extra:
  search:
    lang:
      - en
      - jp
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ShiinaHiiragi
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ShiinaHiiragi
  generator: true
  consent:
    title: Cookie 许可
    description:
      本站使用 Cookie 记录访客偏好，其内容仅保留在本地。若点击「同意」按钮，则视为同意 Cookie 使用；点击底部「Cookie Setting」可随时修改
    cookies:
      github: GitHub
      local: 本地设置
    actions:
      - accept
      - reject

extra_css:
  - assets/config.css

extra_javascript:
  - assets/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

copyright:
  Copyright &copy; <span class="year"></span> Ichinoe – <a href="#__consent"> Cookie Setting </a>

nav:
  - 通用:
    - 介绍: index.md
    - 版式规范: intro/format.md
    - 内容规范: intro/toc.md
  - 认识基础:
    - 一、形式逻辑:
      - 1 概念: cogn/form/cep.md
      - 2 命题与演绎: cogn/form/ded.md
      - 3 归纳和类比: cogn/form/ind.md
      - 4 非形式逻辑: cogn/form/prf.md
    - 二、逻辑语:
      - 1 体系与正字法: cogn/jbo/phone.md
      - 2 词法与构词法: cogn/jbo/lex.md
      - 3 句法与篇章法: cogn/jbo/syntax.md
      - 4 EBNF 句法: cogn/jbo/bnf.md
    - 三、Lean:
      - 1 系统原理: cogn/lean/sys.md
      - 2 句法范畴: cogn/lean/cat.md
      - 3 初始模块: cogn/lean/init.md
      - 4 元编程: cogn/lean/meta.md
  - 形而上学:
    - 一、认知科学:
      - 1 神经认知: meta/cogn/nerve.md
      - 2 心理认知: meta/cogn/psyc.md
      - 3 语言认知: meta/cogn/lang.md
      - 4 思维认知: meta/cogn/think.md
      - 5 文化认知: meta/cogn/civ.md
    - 二、符号学:
      - 1 符号原理: meta/sign/prin.md
      - 2 符号的性质: meta/sign/prop.md
      - 3 符号句法学: meta/sign/syntax.md
      - 4 符号推演: meta/sign/ded.md
      - 5 结构主义: meta/sign/struct.md
    - 三、分析哲学:
      - 1 演绎与证成: meta/logic/syntax.md
      - 2 真理与悖论: meta/logic/truth.md
      - 3 意义与指称: meta/logic/mean.md
      - 4 本体与模态: meta/logic/onto.md
    - 四、数学哲学:
      - 1 基本问题与历史观点: meta/math/cep.md
      - 2 三大主义: meta/math/doctr.md
      - 3 当代观点: meta/math/cont.md
  - 逻辑学:
    - 一、证明论:
      - 1 Hilbert 系统: logic/prf/hilbert.md
      # - 2 自然演绎: logic/prf/nat.md
      # - 3 相继式演算: logic/prf/seq.md
      - 4 非经典逻辑: logic/prf/ncl.md
      - 5 序数分析: logic/prf/ord.md
    - 二、模型论:
      - 1 结构与模型: logic/mdl/mdl.md
      - 2 量词消去: logic/mdl/eoq.md
      - 3 稳定理论: logic/mdl/stb.md
    - 三、递归论:
      - 1 可计算理论: logic/rec/comp.md
      - 2 计算复杂性理论: logic/rec/cplx.md
      - 3 不可解度论: logic/rec/dou.md
      - 4 形式算术: logic/rec/arith.md
      - 5 随机性理论: logic/rec/rand.md
    - 四、公理集合论:
      - 1 数学基础: logic/set/base.md
      - 2 集合代数: logic/set/alg.md
      - 3 序数与基数: logic/set/ord.md
      - 4 集宇宙: logic/set/univ.md
      - 5 高阶无穷: logic/set/card.md
  - 代数学:
    - 一、初等代数:
      - 1 解析式与初等函数: alg/elem/form.md
      - 2 方程与不等式: alg/elem/eq.md
      - 3 矩阵论: alg/elem/mat.md
    - 二、组合数学:
      - 1 初等数论: alg/comb/num.md
      - 2 大数理论: alg/comb/gg.md
      - 3 计数理论: alg/comb/comb.md
      - 4 图论: alg/comb/graph.md
    - 三、近世代数:
      - 1 群论: alg/mod/grp.md
      - 2 环论: alg/mod/ring.md
      - 3 域论: alg/mod/fld.md
      - 4 格论: alg/mod/ltt.md
  - 几何学:
    - 一、解析几何:
      - 1 线性空间与向量: top/anly/lin.md
      - 2 变换与坐标: top/anly/geom.md
      - 3 方程与图形: top/anly/eq.md
      - 4 曲线理论: top/anly/curv.md
      - 5 曲面理论: top/anly/surf.md
    - 二、点集拓扑:
      - 1 拓扑空间: top/point/space.md
      - 2 构造空间: top/point/constr.md
      - 3 拓扑不变性质: top/point/prop.md
  - 分析学:
    - 一、分析学原理:
      - 1 序列与级数: anly/princ/seq.md
      - 2 微分法: anly/princ/diff.md
      - 3 积分法: anly/princ/int.md
    - 二、复分析:
      - 1 复函数: anly/cmplx/func.md
      - 2 微分与积分: anly/cmplx/anly.md
      - 3 留数理论: anly/cmplx/res.md
    - 三、实分析:
      - 1 测度论: anly/real/ms.md
      - 2 微分与积分: anly/real/lbg.md
    - 四、泛函分析:
      - 1 赋范线性空间: anly/func/norm.md
      - 2 算子与泛函: anly/func/op.md
    - 五、概率论:
      - 1 概率与随机变量: stat/prob/prob.md
      - 2 概率分布与特征: stat/prob/dist.md
      - 3 统计独立性: stat/prob/ind.md
      - 4 条件期望: stat/prob/cond.md
  - 语言学:
    - 一、类型论:
      - 1 一般类型论: lang/type/gen.md
      - 2 依值类型论: lang/type/dep.md
      - 3 数学基础: lang/type/math.md
    - 二、形式语言:
      - 1 形式文法与自动机: lang/formal/gr.md
      - 2 形式语义: lang/formal/sem.md
    - 三、自然语言:
      - 1 句法学: lang/nat/syntax.md
      - 2 语义学: lang/nat/semant.md
      - 3 语用学: lang/nat/pragma.md
